### PR TITLE
Update _path.scss

### PR DESCRIPTION
**Pull request by Cedruyne**
Use variable ($ti-font-path) for path 
easy to overload : 
```
$ti-font-path: '~themify-icons/themify-icons/fonts';
@import "~themify-icons/themify-icons/_themify-icons.scss";
```

### CODE REVIEW

**Comment by aastrong** [comment]
Testing this tonight - will merge in if all is good. 
Thx. @Cedruyne and sorry for the slow reply - pretty busy with other things these days.

**Comment by jaumebosch** [comment]
> Testing this tonight - will merge in if all is good.
> Thx. @Cedruyne and sorry for the slow reply - pretty busy with other things these days.

any news about merging?

**Comment by aastrong** [comment]
Merged

**Comment by jaumebosch** [comment]
> Merged

cool!

**Pull request merged**
